language: java
env:
  global:
  - secure: kNnTczWZSlT4XokguN3PVz1D+lqNjwPO09w/9bpKJ+ETJPPvUfbMYB6XwQZx8/kwTAXuytXfvFTpUqCQ3Gqr0ARuQ+tCQ3UNJewoQ2y7lOW9BcADiGxDL5A5N7aVOkSg76zg+6lUj3MWR9wq187MEWwyoLb61V7xVF+wclONUeU=
  - secure: gj+ET01AuduvCv/Ld/+8cAVOGt0e2JfktZVoYM6uJAGVFClIHGp3uOGhojxwsLqf7+FJwDhr/McBJNfSzY3KXZYksh1Mqj0fBd9JN9Nsew3tq9pZD9gzQ0a997TEqUhk9SZ0oeCincaf+9pX5NRE1SmopvQuDS5tG2Se2fQJhSs=
notifications:
  slack:
    secure: EMNAL2NBygK9HV4M7hdcXIlNsNgZKhvwhvgdZHbTfcHekVc6O7i44lx2MaCH72FRP7o+5YWIzVEBEBOWcUbfvzkHN9TuJB0pcFzIbkcqv7awG9gMu9FrvSmUgPOKWnBC4dJrRovVREiiBbYnZlJer6fhN+H7BGIv6zJg5IUdC9M=
deploy:
  provider: releases
  api_key:
    secure: dTs6rgraNytkHy/3OK4muwpIcIKN3pqR6xyChzqgKxrlA4dnLLvainT4gSc+Gq+J28fSEeL5vys2EmQaQhDc7U8ZZswONl0KDzu7QgQ1go7z+KKVxcCB3E90JapqIHoUlikTKeO6uCDhtzJHiuFjmuU8ceHhkqHt0hWQA4SZyZY=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-xlrelease-plugin
