language: java
sudo: false
addons:
  apt:
    packages:
    - httpie
    - jq
env:
  global:
  - WEB_SERVER=http://localhost:15516
  - BROWSER=chrome
  - secure: VfUfSlSH7p0W4ZJUwrY5P+2r9MT+f+SYF3LWfV9wdCcGcn8sTGh3rGozz+f0PQaUVJ1TWZoOXX9xPnkqjf5cII5JgCZANZIh90LyhontOpLNZP5ni/8zHL0Dd7MSzObPmc9W791HjfdjjG7fxeV9u1ZzS8F7kce8OoqOv++PRco=
  - secure: Imqqu6YnSxwuL6TIvDth3HG8nnuAeYrxEJNcVN3DhlITmFbhIC9mPVyC3tOTRuxdKdTZX2sSRr2DSHquunjTNOJrd67UU5jj4PXNuS6vfiX7yahr9BjvQiI+/lRtKfq9badQ5eD1s4xxWJ5gs0x2f4kObvWOsY9AhmNyPEpGdLs=
script:
- mkdir -p ./xl-licenses
- http --print=b --auth $USERNAME:$PASSWORD --json POST https://download.xebialabs.com/api/temporary/xl-release firstName=xlc lastName=xlc email=xlc@xebialabs.com company=xebialabs | jq '.license' > ./xl-licenses/xl-release-license.lic
- "./gradlew clean assemble"
- docker run --rm -d -v $PWD/build/libs/.:/opt/xlr/server/plugins/__local__ -v $PWD/xl-licenses:/license -p 15516:5516 --name xlr xebialabs/xl-docker-demo-xlr:latest
- "./gradlew test"
- docker stop xlr
notifications:
  hipchat:
    rooms:
      secure: j3hkJ/Etd8gQDvhpgwBJhutwFA1vex8Q18FMsfiSih1JDoA+PJNfzyG21UmO0g2CDMBfcniKWTHN6VZpN+jSgeZ+UCbz1NMc8rGT1KgexI6CcH1DLGNFJ1o+5oToNZHfRyA7QB1zJz8q8gxrSVPHdqZgb8doAcvMFK0GqewY9dI=
deploy:
  provider: releases
  api_key:
    secure: IP25v/puP1qgGfCRWG+/7EKDU6pyyaU54WRqqNICi8qcubmXxTmfY6/QJeF2bS+MLFZBfttUjdnHWxOMTWBUAP8HFIRkgGHsFIHxiFYbUaKdRXJOZPElpP08mm7HU1Lz/Tz0rU99ry9TVG28RfmGvpsIM6+OdlG8SDdcESqHacg=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-xlrelease-plugin
