language: java
sudo: false
addons:
  chrome: stable
  apt:
    packages:
    - httpie
    - jq
env:
  global:
  - WEB_SERVER=http://localhost:5516
  - BROWSER=chrome
  - secure: kNnTczWZSlT4XokguN3PVz1D+lqNjwPO09w/9bpKJ+ETJPPvUfbMYB6XwQZx8/kwTAXuytXfvFTpUqCQ3Gqr0ARuQ+tCQ3UNJewoQ2y7lOW9BcADiGxDL5A5N7aVOkSg76zg+6lUj3MWR9wq187MEWwyoLb61V7xVF+wclONUeU=
  - secure: gj+ET01AuduvCv/Ld/+8cAVOGt0e2JfktZVoYM6uJAGVFClIHGp3uOGhojxwsLqf7+FJwDhr/McBJNfSzY3KXZYksh1Mqj0fBd9JN9Nsew3tq9pZD9gzQ0a997TEqUhk9SZ0oeCincaf+9pX5NRE1SmopvQuDS5tG2Se2fQJhSs=
script:
- mkdir -p ./xl-licenses
- http --check-status --print=b --auth $username:$password --json POST https://download.xebialabs.com/api/temporary/xl-release firstName=xlc lastName=xlc email=xlc@xebialabs.com company=xebialabs | jq --raw-output '.license' > ./xl-licenses/xl-release-license.lic
- "./gradlew clean assemble"
- docker run --rm -d -v $PWD/build/libs/.:/opt/xlr/server/plugins/__local__ -v $PWD/xl-licenses:/license
  -p 5516:5516 --name xlr xebialabs/xl-docker-demo-xlr:latest
- sleep 60
- "./gradlew test"
- docker logs xlr
- docker stop xlr
notifications:
  hipchat:
    rooms:
      secure: j3hkJ/Etd8gQDvhpgwBJhutwFA1vex8Q18FMsfiSih1JDoA+PJNfzyG21UmO0g2CDMBfcniKWTHN6VZpN+jSgeZ+UCbz1NMc8rGT1KgexI6CcH1DLGNFJ1o+5oToNZHfRyA7QB1zJz8q8gxrSVPHdqZgb8doAcvMFK0GqewY9dI=
deploy:
  provider: releases
  api_key:
    secure: IP25v/puP1qgGfCRWG+/7EKDU6pyyaU54WRqqNICi8qcubmXxTmfY6/QJeF2bS+MLFZBfttUjdnHWxOMTWBUAP8HFIRkgGHsFIHxiFYbUaKdRXJOZPElpP08mm7HU1Lz/Tz0rU99ry9TVG28RfmGvpsIM6+OdlG8SDdcESqHacg=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-xlrelease-plugin
